spring:
  application:
    name: investor
  datasource:
    url: jdbc:mysql://localhost:3306/shares?serverTimezone=Asia/Shanghai
    username: root
    password: xujinjing
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 60000
      idle-timeout: 60000
      max-lifetime: 0
      minimum-idle: 10
      maximum-pool-size: 10
  task:
    scheduling:
      pool:
        size: 10
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  type-aliases-package: com.jackie.stockbean.investor.entity
  #\u5F00\u542F\u9A7C\u5CF0\u6620\u5C04
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8884
